language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
services:
  - docker
jobs:
  include:
    - stage: build docker image
      script:
        - npm run build
        - docker build -f Dockerfile -t client-maestro .
      after_success:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag client-maestro $DOCKER_USER/$REPO:latest
        - docker tag client-maestro $DOCKER_USER/$REPO:$TRAVIS_BRANCH
        - docker push $DOCKER_USER/$REPO:latest
        - docker push $DOCKER_USER/$REPO:$TRAVIS_BRANCH
